# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sf_cw-icfpc-2017

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sf_cw-icfpc-2017

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_cw-icfpc-2017/CMakeFiles /media/sf_cw-icfpc-2017/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_cw-icfpc-2017/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named punter-greedy

# Build rule for target.
punter-greedy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 punter-greedy
.PHONY : punter-greedy

# fast build rule for target.
punter-greedy/fast:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/build
.PHONY : punter-greedy/fast

#=============================================================================
# Target rules for targets named punter

# Build rule for target.
punter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 punter
.PHONY : punter

# fast build rule for target.
punter/fast:
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/build
.PHONY : punter/fast

#=============================================================================
# Target rules for targets named punter-aggro

# Build rule for target.
punter-aggro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 punter-aggro
.PHONY : punter-aggro

# fast build rule for target.
punter-aggro/fast:
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/build
.PHONY : punter-aggro/fast

#=============================================================================
# Target rules for targets named punter2

# Build rule for target.
punter2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 punter2
.PHONY : punter2

# fast build rule for target.
punter2/fast:
	$(MAKE) -f CMakeFiles/punter2.dir/build.make CMakeFiles/punter2.dir/build
.PHONY : punter2/fast

#=============================================================================
# Target rules for targets named local_runner

# Build rule for target.
local_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 local_runner
.PHONY : local_runner

# fast build rule for target.
local_runner/fast:
	$(MAKE) -f CMakeFiles/local_runner.dir/build.make CMakeFiles/local_runner.dir/build
.PHONY : local_runner/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

local_runner/local_runner.o: local_runner/local_runner.cpp.o

.PHONY : local_runner/local_runner.o

# target to build an object file
local_runner/local_runner.cpp.o:
	$(MAKE) -f CMakeFiles/local_runner.dir/build.make CMakeFiles/local_runner.dir/local_runner/local_runner.cpp.o
.PHONY : local_runner/local_runner.cpp.o

local_runner/local_runner.i: local_runner/local_runner.cpp.i

.PHONY : local_runner/local_runner.i

# target to preprocess a source file
local_runner/local_runner.cpp.i:
	$(MAKE) -f CMakeFiles/local_runner.dir/build.make CMakeFiles/local_runner.dir/local_runner/local_runner.cpp.i
.PHONY : local_runner/local_runner.cpp.i

local_runner/local_runner.s: local_runner/local_runner.cpp.s

.PHONY : local_runner/local_runner.s

# target to generate assembly for a file
local_runner/local_runner.cpp.s:
	$(MAKE) -f CMakeFiles/local_runner.dir/build.make CMakeFiles/local_runner.dir/local_runner/local_runner.cpp.s
.PHONY : local_runner/local_runner.cpp.s

model/Empire.o: model/Empire.cpp.o

.PHONY : model/Empire.o

# target to build an object file
model/Empire.cpp.o:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/model/Empire.cpp.o
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/model/Empire.cpp.o
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/model/Empire.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/model/Empire.cpp.o
.PHONY : model/Empire.cpp.o

model/Empire.i: model/Empire.cpp.i

.PHONY : model/Empire.i

# target to preprocess a source file
model/Empire.cpp.i:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/model/Empire.cpp.i
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/model/Empire.cpp.i
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/model/Empire.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/model/Empire.cpp.i
.PHONY : model/Empire.cpp.i

model/Empire.s: model/Empire.cpp.s

.PHONY : model/Empire.s

# target to generate assembly for a file
model/Empire.cpp.s:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/model/Empire.cpp.s
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/model/Empire.cpp.s
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/model/Empire.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/model/Empire.cpp.s
.PHONY : model/Empire.cpp.s

model/GameState.o: model/GameState.cpp.o

.PHONY : model/GameState.o

# target to build an object file
model/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/model/GameState.cpp.o
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/model/GameState.cpp.o
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/model/GameState.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/model/GameState.cpp.o
.PHONY : model/GameState.cpp.o

model/GameState.i: model/GameState.cpp.i

.PHONY : model/GameState.i

# target to preprocess a source file
model/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/model/GameState.cpp.i
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/model/GameState.cpp.i
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/model/GameState.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/model/GameState.cpp.i
.PHONY : model/GameState.cpp.i

model/GameState.s: model/GameState.cpp.s

.PHONY : model/GameState.s

# target to generate assembly for a file
model/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/model/GameState.cpp.s
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/model/GameState.cpp.s
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/model/GameState.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/model/GameState.cpp.s
.PHONY : model/GameState.cpp.s

punter/OfflineProtocol.o: punter/OfflineProtocol.cpp.o

.PHONY : punter/OfflineProtocol.o

# target to build an object file
punter/OfflineProtocol.cpp.o:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/punter/OfflineProtocol.cpp.o
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/punter/OfflineProtocol.cpp.o
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/punter/OfflineProtocol.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/punter/OfflineProtocol.cpp.o
.PHONY : punter/OfflineProtocol.cpp.o

punter/OfflineProtocol.i: punter/OfflineProtocol.cpp.i

.PHONY : punter/OfflineProtocol.i

# target to preprocess a source file
punter/OfflineProtocol.cpp.i:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/punter/OfflineProtocol.cpp.i
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/punter/OfflineProtocol.cpp.i
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/punter/OfflineProtocol.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/punter/OfflineProtocol.cpp.i
.PHONY : punter/OfflineProtocol.cpp.i

punter/OfflineProtocol.s: punter/OfflineProtocol.cpp.s

.PHONY : punter/OfflineProtocol.s

# target to generate assembly for a file
punter/OfflineProtocol.cpp.s:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/punter/OfflineProtocol.cpp.s
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/punter/OfflineProtocol.cpp.s
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/punter/OfflineProtocol.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/punter/OfflineProtocol.cpp.s
.PHONY : punter/OfflineProtocol.cpp.s

punter/punter.o: punter/punter.cpp.o

.PHONY : punter/punter.o

# target to build an object file
punter/punter.cpp.o:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/punter/punter.cpp.o
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/punter/punter.cpp.o
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/punter/punter.cpp.o
.PHONY : punter/punter.cpp.o

punter/punter.i: punter/punter.cpp.i

.PHONY : punter/punter.i

# target to preprocess a source file
punter/punter.cpp.i:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/punter/punter.cpp.i
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/punter/punter.cpp.i
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/punter/punter.cpp.i
.PHONY : punter/punter.cpp.i

punter/punter.s: punter/punter.cpp.s

.PHONY : punter/punter.s

# target to generate assembly for a file
punter/punter.cpp.s:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/punter/punter.cpp.s
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/punter/punter.cpp.s
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/punter/punter.cpp.s
.PHONY : punter/punter.cpp.s

punter2/punter2.o: punter2/punter2.cpp.o

.PHONY : punter2/punter2.o

# target to build an object file
punter2/punter2.cpp.o:
	$(MAKE) -f CMakeFiles/punter2.dir/build.make CMakeFiles/punter2.dir/punter2/punter2.cpp.o
.PHONY : punter2/punter2.cpp.o

punter2/punter2.i: punter2/punter2.cpp.i

.PHONY : punter2/punter2.i

# target to preprocess a source file
punter2/punter2.cpp.i:
	$(MAKE) -f CMakeFiles/punter2.dir/build.make CMakeFiles/punter2.dir/punter2/punter2.cpp.i
.PHONY : punter2/punter2.cpp.i

punter2/punter2.s: punter2/punter2.cpp.s

.PHONY : punter2/punter2.s

# target to generate assembly for a file
punter2/punter2.cpp.s:
	$(MAKE) -f CMakeFiles/punter2.dir/build.make CMakeFiles/punter2.dir/punter2/punter2.cpp.s
.PHONY : punter2/punter2.cpp.s

solver/Solver.o: solver/Solver.cpp.o

.PHONY : solver/Solver.o

# target to build an object file
solver/Solver.cpp.o:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/solver/Solver.cpp.o
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/solver/Solver.cpp.o
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/solver/Solver.cpp.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/solver/Solver.cpp.o
.PHONY : solver/Solver.cpp.o

solver/Solver.i: solver/Solver.cpp.i

.PHONY : solver/Solver.i

# target to preprocess a source file
solver/Solver.cpp.i:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/solver/Solver.cpp.i
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/solver/Solver.cpp.i
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/solver/Solver.cpp.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/solver/Solver.cpp.i
.PHONY : solver/Solver.cpp.i

solver/Solver.s: solver/Solver.cpp.s

.PHONY : solver/Solver.s

# target to generate assembly for a file
solver/Solver.cpp.s:
	$(MAKE) -f CMakeFiles/punter-greedy.dir/build.make CMakeFiles/punter-greedy.dir/solver/Solver.cpp.s
	$(MAKE) -f CMakeFiles/punter.dir/build.make CMakeFiles/punter.dir/solver/Solver.cpp.s
	$(MAKE) -f CMakeFiles/punter-aggro.dir/build.make CMakeFiles/punter-aggro.dir/solver/Solver.cpp.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/solver/Solver.cpp.s
.PHONY : solver/Solver.cpp.s

tests/OfflineProtocolTest.o: tests/OfflineProtocolTest.cpp.o

.PHONY : tests/OfflineProtocolTest.o

# target to build an object file
tests/OfflineProtocolTest.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/OfflineProtocolTest.cpp.o
.PHONY : tests/OfflineProtocolTest.cpp.o

tests/OfflineProtocolTest.i: tests/OfflineProtocolTest.cpp.i

.PHONY : tests/OfflineProtocolTest.i

# target to preprocess a source file
tests/OfflineProtocolTest.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/OfflineProtocolTest.cpp.i
.PHONY : tests/OfflineProtocolTest.cpp.i

tests/OfflineProtocolTest.s: tests/OfflineProtocolTest.cpp.s

.PHONY : tests/OfflineProtocolTest.s

# target to generate assembly for a file
tests/OfflineProtocolTest.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/OfflineProtocolTest.cpp.s
.PHONY : tests/OfflineProtocolTest.cpp.s

tests/SolverTests.o: tests/SolverTests.cpp.o

.PHONY : tests/SolverTests.o

# target to build an object file
tests/SolverTests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/SolverTests.cpp.o
.PHONY : tests/SolverTests.cpp.o

tests/SolverTests.i: tests/SolverTests.cpp.i

.PHONY : tests/SolverTests.i

# target to preprocess a source file
tests/SolverTests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/SolverTests.cpp.i
.PHONY : tests/SolverTests.cpp.i

tests/SolverTests.s: tests/SolverTests.cpp.s

.PHONY : tests/SolverTests.s

# target to generate assembly for a file
tests/SolverTests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/SolverTests.cpp.s
.PHONY : tests/SolverTests.cpp.s

tests/TestGameState.o: tests/TestGameState.cpp.o

.PHONY : tests/TestGameState.o

# target to build an object file
tests/TestGameState.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/TestGameState.cpp.o
.PHONY : tests/TestGameState.cpp.o

tests/TestGameState.i: tests/TestGameState.cpp.i

.PHONY : tests/TestGameState.i

# target to preprocess a source file
tests/TestGameState.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/TestGameState.cpp.i
.PHONY : tests/TestGameState.cpp.i

tests/TestGameState.s: tests/TestGameState.cpp.s

.PHONY : tests/TestGameState.s

# target to generate assembly for a file
tests/TestGameState.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/TestGameState.cpp.s
.PHONY : tests/TestGameState.cpp.s

tests/tests-main.o: tests/tests-main.cpp.o

.PHONY : tests/tests-main.o

# target to build an object file
tests/tests-main.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/tests-main.cpp.o
.PHONY : tests/tests-main.cpp.o

tests/tests-main.i: tests/tests-main.cpp.i

.PHONY : tests/tests-main.i

# target to preprocess a source file
tests/tests-main.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/tests-main.cpp.i
.PHONY : tests/tests-main.cpp.i

tests/tests-main.s: tests/tests-main.cpp.s

.PHONY : tests/tests-main.s

# target to generate assembly for a file
tests/tests-main.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/tests-main.cpp.s
.PHONY : tests/tests-main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... punter-greedy"
	@echo "... punter"
	@echo "... punter-aggro"
	@echo "... punter2"
	@echo "... local_runner"
	@echo "... tests"
	@echo "... local_runner/local_runner.o"
	@echo "... local_runner/local_runner.i"
	@echo "... local_runner/local_runner.s"
	@echo "... model/Empire.o"
	@echo "... model/Empire.i"
	@echo "... model/Empire.s"
	@echo "... model/GameState.o"
	@echo "... model/GameState.i"
	@echo "... model/GameState.s"
	@echo "... punter/OfflineProtocol.o"
	@echo "... punter/OfflineProtocol.i"
	@echo "... punter/OfflineProtocol.s"
	@echo "... punter/punter.o"
	@echo "... punter/punter.i"
	@echo "... punter/punter.s"
	@echo "... punter2/punter2.o"
	@echo "... punter2/punter2.i"
	@echo "... punter2/punter2.s"
	@echo "... solver/Solver.o"
	@echo "... solver/Solver.i"
	@echo "... solver/Solver.s"
	@echo "... tests/OfflineProtocolTest.o"
	@echo "... tests/OfflineProtocolTest.i"
	@echo "... tests/OfflineProtocolTest.s"
	@echo "... tests/SolverTests.o"
	@echo "... tests/SolverTests.i"
	@echo "... tests/SolverTests.s"
	@echo "... tests/TestGameState.o"
	@echo "... tests/TestGameState.i"
	@echo "... tests/TestGameState.s"
	@echo "... tests/tests-main.o"
	@echo "... tests/tests-main.i"
	@echo "... tests/tests-main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

